services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nova-rio-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env.production
    networks:
      - nova-rio-network

networks:
  nova-rio-network:
    external: true
